//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REDES_1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public long cc { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string ciudad { get; set; }
        public long tel { get; set; }
        public string usuario { get; set; }
        public string contra { get; set; }
    }
}
